package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildAggregation'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildAggregation")) {
    dependencies {
        expect(RelativeId("BuildMacOS")) {
            snapshot {
            }

            artifacts {
                artifactRules = "CinecoderSamples-MacOS-%teamcity.build.branch%-%build.number%.zip"
            }
        }
        update(RelativeId("BuildMacOS")) {
            artifacts {
                artifactRules = "CinecoderSamples-MacOS-%teamcity.build.branch%-%build.number%.zip"
                enabled = false
            }
        }

    }
}
