package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildWin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildWin")) {
    check(artifactRules == """
        _bin\Release.x64 => CinecoderSamples-Win64-%teamcity.build.branch%-%build.number%.zip
        common\cinecoder_license_string.* => LicenseIncludes-%teamcity.build.branch%-%build.number%.zip
    """.trimIndent()) {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        _bin\Release.x64 => CinecoderSamples-Win64-%teamcity.build.branch%-%build.number%.zip
        _bin\Release.ARM64 => CinecoderSamples-WinARM64-%teamcity.build.branch%-%build.number%.zip
        common\cinecoder_license_string.* => LicenseIncludes-%teamcity.build.branch%-%build.number%.zip
    """.trimIndent()
}
