package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildLinuxArm64'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildLinuxArm64")) {
    expectSteps {
        exec {
            name = "(patch) Version (from version step)"
            path = "pwsh"
            arguments = "./set_version.ps1 -majorVer %dep.Cinecoder_Samples_Version.MajorVersion% -minorVer %dep.Cinecoder_Samples_Version.MinorVersion%  -buildVer %dep.Cinecoder_Samples_Version.BuildVersion%  -sourceVer %dep.Cinecoder_Samples_Version.SourceVersion%"
            dockerImage = "registry.cinegy.com/docker/docker-builds/ubuntu1804/devbase:latest"
            dockerImagePlatform = ExecBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
        exec {
            name = "(patch) Inject license"
            workingDir = "common"
            path = "pwsh"
            arguments = "./inject-license.ps1 -CompanyName %dep.Cinecoder_Samples_Version.LICENSE_COMPANYNAME% -LicenseKey %LICENSE_KEY%"
            dockerImage = "registry.cinegy.com/docker/docker-builds/ubuntu1804/devbase:latest"
            dockerImagePlatform = ExecBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
        exec {
            name = "(build) Samples Script"
            path = "./build_samples-linux-arm64.sh"
            arguments = "Release --platform=linux/arm64"
            dockerImage = "registry.cinegy.com/docker/docker-builds/ubuntu2004/devbasearm64:latest"
            dockerImagePlatform = ExecBuildStep.ImagePlatform.Linux
            dockerPull = true
        }
    }
    steps {
        update<ExecBuildStep>(2) {
            clearConditions()
            arguments = "Release 8"
        }
    }
}
