package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildLinuxArm64'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildLinuxArm64")) {
    check(artifactRules == "_bin/linux => CinecoderSamples-Linux-Arm64-%teamcity.build.branch%-%build.number%.zip") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "_bin/linux.aarch64 => CinecoderSamples-Linux-Arm64-%teamcity.build.branch%-%build.number%.zip"
}
