package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildWin'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildWin")) {
    params {
        expect {
            password("LICENSE_KEY", "zxxa438a776e2232213653a573da6eb2734dca83fc076d4ebe9c9ee46ce2dcfcf2daf64a0983187fa7e2782eea53ed0acfa9545bd6184f6c2d3ee310aba0bcd293b775d03cbe80d301b", label = "License key", description = "Value to use for integrated Cinecoder license key", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("LICENSE_KEY", "credentialsJSON:3232fa18-602e-4414-80d5-9901a79cfc16", label = "License key", description = "Value to use for integrated Cinecoder license key", display = ParameterDisplay.HIDDEN)
        }
    }
}
